package com.mimir.app.service;

import java.util.List;
import java.util.stream.IntStream;

import com.mimir.app.domain.RetrievedChunk;

public interface RerankerClient {

    /**
     * Minimum relevance score a chunk must have to be considered usable context.
     * Tune based on observed score distributions from your reranker model.
     */
    float MIN_RELEVANCE_SCORE = 0.5f;

    /**
     * Returns relevance scores aligned with input chunks.
     * Yes, these scores are generated by a machine learning model. They represent how relevant each chunk is to the query,
     * based on understanding both the question and the content together.
     * Rerankers use a Transformer-based neural network (cross-encoder) trained to produce a relevance score
     */
    List<Float> score(String query, List<RetrievedChunk> chunks);

    /**
     * Convenience method → applies sorting using scores, then filters out
     * low-relevance chunks before truncating to topK.
     * Default implementation to avoid duplication.
     */
    default List<RetrievedChunk> rerank(String query, List<RetrievedChunk> candidates, int topK) {

        if (candidates == null || candidates.isEmpty()) {
            return List.of();
        }

        List<Float> scores = score(query, candidates);

        // Safety check
        if (scores.size() != candidates.size()) {
            return candidates.stream()
                    .sorted((a, b) -> Float.compare(b.getScore(), a.getScore()))
                    .filter(c -> c.getScore() >= MIN_RELEVANCE_SCORE)
                    .limit(topK)
                    .toList();
        }

        return IntStream.range(0, candidates.size())
                .mapToObj(i -> {
                    RetrievedChunk c = candidates.get(i);
                    return RetrievedChunk.builder()
                            .content(c.getContent())
                            .embedding(c.getEmbedding())
                            .metadata(c.getMetadata())
                            .score(scores.get(i))
                            .build();
                })
                .sorted((a, b) -> Float.compare(b.getScore(), a.getScore()))
                .filter(c -> c.getScore() >= MIN_RELEVANCE_SCORE)
                .limit(topK)
                .toList();
    }
}
